"""op별 응답 필드 → 한글 라벨 (서비스설계서 '응답 메시지 명세' 기준).

프론트 표시/카드뉴스 매핑용. 실제 응답에 없는 필드는 그냥 안 나옴.
"""

FIELD_LABELS = {
    "business": {
        "biz_category_cd": "사업 구분 코드",
        "supt_biz_titl_nm": "사업명",
        "biz_supt_trgt_info": "지원 대상",
        "biz_supt_bdgt_info": "지원예산 및 규모",
        "biz_supt_ctnt": "지원 내용",
        "supt_biz_chrct": "지원 특징",
        "supt_biz_intrd_info": "사업 소개",
        "biz_yr": "사업 연도",
        "detl_pg_url": "상세페이지 URL",
    },
    "announcement": {
        "intg_pbanc_yn": "통합공고 여부",
        "intg_pbanc_biz_nm": "통합공고 사업명",
        "biz_pbanc_nm": "지원사업 공고명",
        "pbanc_ctnt": "공고 내용",
        "supt_biz_clsfc": "지원 분야",
        "aply_trgt_ctnt": "신청 대상 내용",
        "supt_regin": "지역명",
        "pbanc_rcpt_bgng_dt": "공고 접수 시작일시",
        "pbanc_rcpt_end_dt": "공고 접수 종료일시",
        "pbanc_ntrp_nm": "창업지원 기관명",
        "sprv_inst": "주관 기관",
        "biz_prch_dprt_nm": "사업 담당부서명",
        "biz_gdnc_url": "사업 안내 URL",
        "biz_aply_url": "사업 신청 URL",
        "prch_cnpl_no": "담당자 연락처",
        "detl_pg_url": "상세페이지 URL",
        "aply_mthd_vst_rcpt_istc": "신청방법(방문)",
        "aply_mthd_pssr_rcpt_istc": "신청방법(우편)",
        "aply_mthd_fax_rcpt_istc": "신청방법(팩스)",
        "aply_mthd_eml_rcpt_istc": "신청방법(이메일)",
        "aply_mthd_onli_rcpt_istc": "신청방법(온라인)",
        "aply_mthd_etc_istc": "신청방법(기타)",
        "aply_excl_trgt_ctnt": "신청제외 대상내용",
        "aply_trgt": "신청 대상",
        "biz_enyy": "창업 기간",
        "biz_trgt_age": "대상 연령",
        "prfn_matr": "우대 사항",
        "rcrt_prgs_yn": "모집진행 여부",
        "pbanc_sn": "공고 일련번호",
    },
    "content": {
        "clss_cd": "콘텐츠 구분 코드",
        "titl_nm": "제목",
        "fstm_reg_dt": "등록 일시",
        "view_cnt": "조회 수",
        "detl_pg_url": "상세페이지 URL",
        "file_nm": "파일명",
    },
    "statistics": {
        "titl_nm": "통계자료명",
        "ctnt": "통계자료 내용",
        "fstm_reg_dt": "등록 일시",
        "last_mdfcn_dt": "수정 일시",
        "detl_pg_url": "상세페이지 URL",
        "file_nm": "다운로드 파일명",
    },
    "corporate": {
        "confmdoc_isu_no": "창업기업확인서 발급번호",
        "ntrp_type_nm": "기업 구분",
        "ntrp_nm": "기업명",
        "brno": "사업자등록번호",
        "repr_nm": "대표자명",
        "unin_repr_nm": "공동대표명",
        "crno": "법인등록번호",
        "confmdoc_isu_dt": "확인서 발급일시",
        "confmdoc_expr_dt": "확인서 만료일시",
    },
    "product": {
        "ntrp_nm": "기업명",
        "confmdoc_isu_no": "확인서 발급번호",
        "brno": "사업자등록번호",
        "lwdg_nm": "기업 법정동 지역",
        "manu_nm": "제품명",
        "confmdoc_isu_dt": "확인서 발급일시",
        "confmdoc_expr_dt": "확인서 만료일시",
        "manu_intrd": "제품 소개",
        "manu_stnds": "규격",
        "manu_prc": "제품 가격",
        "hmpg": "제품 URL",
    },
    "education": {},  # 설계서 미제공 → 실제 응답으로 확정 필요
}
